# Use root/example as user/password credentials
version: '3.1'

services:

  flaskblog:
    image: flaskblog:latest
    hostname: flask-web
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      FLASK_ENV: development
    ports:
      - 80:80
    links:
      - "db:database"
    depends_on:
      - db

  db:
    image: mysql
    hostname: mysql_server
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
    ports:
      - 8081:8081
      - 3306:3306
      - 33060:33060

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080