# Use root/example as user/password credentials
version: '3.1'

services:

  flaskblog:
    image: flaskblog:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      FLASK_ENV: development
    ports:
    - 5000:5000

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
    ports:
      - 8081:8081
      - 3306:3306
      - 33060:33060

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080